// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Eshbx5i6tPNjJVPsjN7khI2uHswkxsk',
    appId: '1:893896443845:web:5e9d6f714fd1be86836dac',
    messagingSenderId: '893896443845',
    projectId: 'coworking-45731',
    authDomain: 'coworking-45731.firebaseapp.com',
    databaseURL: 'https://coworking-45731-default-rtdb.firebaseio.com',
    storageBucket: 'coworking-45731.appspot.com',
    measurementId: 'G-ZQ2EWQ7S73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcw9skxnPCrfRDCl2e60vdkzgnU0JEHU',
    appId: '1:893896443845:android:90a19226720e7a0e836dac',
    messagingSenderId: '893896443845',
    projectId: 'coworking-45731',
    databaseURL: 'https://coworking-45731-default-rtdb.firebaseio.com',
    storageBucket: 'coworking-45731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHgZOnFaLvT5G-G5_ZltqQOub8sIvI_c0',
    appId: '1:893896443845:ios:636747eaaa797535836dac',
    messagingSenderId: '893896443845',
    projectId: 'coworking-45731',
    databaseURL: 'https://coworking-45731-default-rtdb.firebaseio.com',
    storageBucket: 'coworking-45731.appspot.com',
    iosBundleId: 'com.example.coworking',
  );
}
